### ISSUE TITLE
Improve documentation README.md

### ISSUE THREAD

**Issue by Bartel-C8** [netless-io/electron-extension-vendor#20]
Hi!

Thank you for this library.
Was using electron-devtools-installer before, but unfortunately is a bit unmaintained.

In the Readme there are some errors/improvements possible though:

My working snippet:

```
import path from "path";
import { app, session } from "electron";

app.whenReady().then(async () => {
  if (process.env.NODE_ENV === "development") {
    await installExtensions();
  }
});

const installExtensions = async () => {
  try {
    const { REACT_DEVELOPER_TOOLS, REDUX_DEVTOOLS } = await require("electron-devtools-vendor");
    session.defaultSession.loadExtension(path.resolve(REACT_DEVELOPER_TOOLS), {
      allowFileAccess: true,
    });
    session.defaultSession.loadExtension(path.resolve(REDUX_DEVTOOLS), {
      allowFileAccess: true,
    });
  } catch (e: any) {
    console.log(`Error installing extension: ${e}`);
  }
};
```

So:
- `REACT_DEVTOOLS` is still used in the example, but it has been renamed to `REACT_DEVELOPER_TOOLS`
- `session` cannot be used directly? I had to reference `defaultSession`? (Electron 16/17)
- Had to add a `path.resolve()` because I got an error: `(node:39397) UnhandledPromiseRejectionWarning: Error: The path to the extension in 'loadExtension' must be absolute`
- Added await before dynamic require, but maybe even now a static import is possible?

**Comment by BlackHole1** [comment]
Thank you for your feedback, I will look at these issues in the next few days.

**Comment by BlackHole1** [comment]
1. Fixed: https://github.com/BlackHole1/electron-devtools-vendor/pull/21
2. Fixed: https://github.com/BlackHole1/electron-devtools-vendor/pull/22
3. I did not reproduce it locally, can you provide an example? (my gist code: https://gist.github.com/97125bbf31a33efd6d977819132f74ea)
4. The static import issue is a bit of a problem, as the library is essentially not needed in a production environment. A static import will have a strong dependency on `tree shaking`. To be on the safe side, I prefer to use the dynamic require for importing.

**Comment by Bartel-C8** [comment]
Thanks for your quick fixes!

For 3: I am using electron-webpack as development provider ( "dev": "electron-webpack dev" ), so maybe it resolves paths differently.
And I see indeed that if I log the import value:
```
    const { REACT_DEVELOPER_TOOLS, REDUX_DEVTOOLS } = await require("electron-devtools-vendor");
    console.log(REACT_DEVELOPER_TOOLS);
```
I get the value: `node_modules/electron-devtools-vendor/extensions/react-developer-tools` , which is not absolute :-). 
PS: In your gist the `.defaultSession` needs to be added as well.

4: Okay thank you for the clarification. The `await` I added to make typescript (TS) happy for dynamic imports.

**Comment by BlackHole1** [comment]
For 3: 
This is the expected webpack behaviour. see: https://stackoverflow.com/a/43527213/6596777
You need to explicitly declare that you need `__driname` in webpack for this to work.

You can add your custom webpack configuration in this way: https://webpack.electron.build/configuration

**Comment by BlackHole1** [comment]
If you have any further questions, I will reply as soon as possible. If not, in 24 hours I will release the version carrying the bug fixes.

**Comment by Bartel-C8** [comment]
Thanks! For me it works with the `path.resolve`, so I'll keep that approach, so I don't have to mess (even for development builds) with my webpack config. (The reason why I use `electron-webpack` 😆 )

Additional comment:

It would be nice if you could link to npm in the Readme as well (click the npm button, now it just links to the image).
And add some keywords in your package.json to be better searchable on npm / Google ;-). 

But the issue may be closed for me, thanks!

**Comment by BlackHole1** [comment]
> It would be nice if you could link to npm in the Readme as well (click the npm button, now it just links to the image).
And add some keywords in your package.json to be better searchable on npm / Google ;-).

Good Idea!

**Comment by BlackHole1** [comment]
> It would be nice if you could link to npm in the Readme as well (click the npm button, now it just links to the image).
And add some keywords in your package.json to be better searchable on npm / Google ;-).

Done

* https://github.com/BlackHole1/electron-devtools-vendor/pull/23
* https://github.com/BlackHole1/electron-devtools-vendor/pull/24

release new version: **[v1.0.4](https://github.com/BlackHole1/electron-devtools-vendor/releases/tag/v1.0.4)**
