### ISSUE TITLE
Terminating extension renderer for bad IPC message

### ISSUE THREAD

**Issue by zyk-mjzs** [netless-io/electron-extension-vendor#29]
crash after restart electron main process occasionally

---

electron version                17.1.2

os mac mini(M1, 2020)    11.6.2

plugin version                    1.0.5

used in [https://github.com/umbrella22/electron-vite-template.git](https://github.com/umbrella22/electron-vite-template.git)

---

![F0F3CE68-6847-4CE8-9B3F-342DF6CD4894](https://user-images.githubusercontent.com/32771265/158502526-54068b39-3c49-4d25-86bd-61c90c6855c8.png)
![QQ20220316-100634](https://user-images.githubusercontent.com/32771265/158502542-fdcff48f-4424-4623-b895-6b4c92b69e87.png)

**Comment by BlackHole1** [comment]
I have not reproduced it locally. try:

<img width="883" alt="image" src="https://user-images.githubusercontent.com/8198408/158504830-7c04c82f-4feb-4c64-ab90-365633bb1008.png">
