### ISSUE TITLE
Warning in electron18

### ISSUE THREAD

**Issue by umbrella22** [netless-io/electron-extension-vendor#30]
![3}YL2}2CG117S)HT3{Y}02](https://user-images.githubusercontent.com/19886152/161072534-2ced665e-2495-46a2-93c2-e45d1e785b4e.png)

**Comment by BlackHole1** [comment]
See: https://developer.chrome.com/blog/mv2-transition/

There are two options to address this issue:
1. electron-devtools-vendor automatically modifies v2 to v3
2. waiting for plugin update

Personally, I would be more in favour of the second approach, the first of which could lead to unforeseen circumstances.

**Comment by Bartel-C8** [comment]
Same goes for (Electron 18.2.0):

```
┏ Electron -------------------

  (node:80082) ExtensionLoadWarning: Warnings loading extension at ./node_modules/electron-devtools-vendor/extensions/react-developer-tools:
    Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
  
  (Use `Electron --trace-warnings ...` to show where the warning was created)

┗ ----------------------------
┏ Electron -------------------

  (node:80082) ExtensionLoadWarning: Warnings loading extension at ./node_modules/electron-devtools-vendor/extensions/redux-devtools:
    Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

┗ ----------------------------
```

For Redux-Devtools this is tracked here: https://github.com/reduxjs/redux-devtools/issues/1037
And I created one for React DevTools just now: https://github.com/facebook/react/issues/24522

**Comment by SijaanX** [comment]
Can you help reproduce this issue?

**Comment by BlackHole1** [comment]
It looks like it is close to being repaired
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/8198408/176813405-57b7a3f8-d20c-4421-9fcd-7ad436d7ad00.png">

**Comment by Haleclipse** [comment]
vue3 should use VUEJS_DEVTOOLS (nhdogjmejiglipccpnnnanhbledajbpd) instead of VUEJS3_DEVTOOLS (ljjemllljcmogpfapbkkighbhhppjdbg), because the so-called Beta version has not been maintained for a long time.

As for the Manifest version 2 upgrade to 3 it is said that it is expected to be completed in Sep.

**Comment by Bartel-C8** [comment]
React devtools is updated in the Chrome extension store! https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi
@BlackHole1 , could you update this one? Thanks!

EDIT: Redux-devtools got a (minor) upgrade as well, but no manifest V3 yet https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd

**Comment by BlackHole1** [comment]
Version released!

- https://github.com/BlackHole1/electron-devtools-vendor/releases/tag/v1.2.0
- https://www.npmjs.com/package/electron-devtools-vendor
- https://github.com/BlackHole1/electron-devtools-vendor/pull/33
- https://github.com/BlackHole1/electron-devtools-vendor/pull/34

**Comment by Bartel-C8** [comment]
Thx for the update, unfortunately unusable just yet due to this Electron bug: https://github.com/electron/electron/issues/36545
