### ISSUE TITLE
REQ: Update react-devtools

### ISSUE THREAD

**Issue by Bartel-C8** [netless-io/electron-extension-vendor#35]
Hi,

A lot of work has happened at Electron to make the manifest V3 happen, and to make React Devtools working again.
Some report it it working, others don't.
The latest version in this repo does not work at least... But React Devtools also released quite some changes.

Would it be update to the latest React Devtools version and create a new release of this package?
https://chromewebstore.google.com/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi

Thanks!

**Comment by BlackHole1** [comment]
v2.0.0 has been released

**Comment by Bartel-C8** [comment]
@BlackHole1 : I had some issues with using this latest version, where react devtools won't work... Apparently it's because `scripting` is not listed under `permissions` in the manifest.json file, although it should be there in the original sources.

Caused by the lint script: https://github.com/BlackHole1/electron-devtools-vendor/blob/main/scripts/lint.js#L58


EDIT: Was too quick with putting screenshots. Compared to the wrong extracted folder. Versioning is fine!

![Screenshot 2023-11-24 at 14 02 28](https://github.com/BlackHole1/electron-devtools-vendor/assets/76486925/7a4de532-21b2-488d-b204-be1bcfed4965)

![Screenshot 2023-11-24 at 14 00 43](https://github.com/BlackHole1/electron-devtools-vendor/assets/76486925/a91d94f3-0939-445b-8056-f346d6676994)


Could you update the complete folder for React Devtools please? Without altering the permissions of `scripting`?

But I have another issue, that version 4.28.5 is not working for local files, but 4.27.0 is ...

Thanks!

**Comment by BlackHole1** [comment]
Thank you for your feedback, but it is currently the weekend (UTC+8), so I may not be able to update promptly. I will make the updates next Monday.

**Comment by BlackHole1** [comment]
v2.0.1 has been released

**Comment by Bartel-C8** [comment]
Sorry, but react-devtools still don't work when loading local files in Electron...

It's caused by the missing `"<all_urls>"` under `host_permissions`

![Screenshot 2023-11-27 at 08 54 28](https://github.com/BlackHole1/electron-devtools-vendor/assets/76486925/7b06f3e3-5d8a-4fde-8fd7-17c8e3bb04e3)


Also, there are extra files in the unpacked extension folders... I assume they are old files which do not exist in current versions anymore. Maybe the extract script should first clear all files and then extract the content again?

![Screenshot 2023-11-27 at 08 54 20](https://github.com/BlackHole1/electron-devtools-vendor/assets/76486925/816bdfff-46e5-48f6-bfc5-f905e8b31a61)

You also see it in the repo these are old (unupdated) files: https://github.com/BlackHole1/electron-devtools-vendor/tree/main/extensions/react-developer-tools/build


Thanks for you work on this, much appreciated!! 🙏

**Comment by BlackHole1** [comment]
@Bartel-C8 Thank you for your feedback. v2.1.0 has been released

**Comment by Bartel-C8** [comment]
Works perfect now! Thank you very much!!
