### ISSUE TITLE
Support Manifest v3

### ISSUE THREAD

**Issue by KSneijders** [netless-io/electron-extension-vendor#43]
Hey! Is it possible to support Manifest v3. I'm using a template for electron which uses the vue devtools which are loaded through this package. 

I get the following error:

```
┏ Electron -------------------

  (node:78916) ExtensionLoadWarning: Warnings loading extension at C:\Users\<user>\<path>\node_modules\electron-devtools-vendor\extensions\vuejs-devtools:
    'host_permissions' requires manifest version of at least 3.
    Manifest version 2 is deprecated, and support will be removed in 2024. See https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline for details.
    'scripting' requires manifest version of at least 3.

  (Use `electron --trace-warnings ...` to show where the warning was created)

┗ ----------------------------
```

I'm not too familiar with the Manifest files, but the this is the refactor that was done in the Vue Dev tools repository to support Manifest V3.

https://github.com/vuejs/devtools/pull/2136/files

**Comment by BlackHole1** [comment]
Done. New Version is `3.0.0`.

**Comment by KSneijders** [comment]
Thank you!

**Comment by KSneijders** [comment]
@BlackHole1 Is it possible the package hasn't been updated in NPM yet? 

https://www.npmjs.com/package/electron-devtools-vendor/v/2.1.0?activeTab=versions

**Comment by BlackHole1** [comment]
WOW. Sorry, I forget it😅

**Comment by BlackHole1** [comment]
Published: https://www.npmjs.com/package/electron-devtools-vendor/v/3.0.0

**Comment by KSneijders** [comment]
Awesome! ❤️
